//go:build !ignore_autogenerated

/*
Copyright 2024 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	storagev1alpha1 "github.com/deckhouse/state-snapshotter/api/storage/v1alpha1"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoObjectRef) DeepCopyInto(out *DemoObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoObjectRef.
func (in *DemoObjectRef) DeepCopy() *DemoObjectRef {
	if in == nil {
		return nil
	}
	out := new(DemoObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDisk) DeepCopyInto(out *DemoVirtualDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDisk.
func (in *DemoVirtualDisk) DeepCopy() *DemoVirtualDisk {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskDataSource) DeepCopyInto(out *DemoVirtualDiskDataSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskDataSource.
func (in *DemoVirtualDiskDataSource) DeepCopy() *DemoVirtualDiskDataSource {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskList) DeepCopyInto(out *DemoVirtualDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskList.
func (in *DemoVirtualDiskList) DeepCopy() *DemoVirtualDiskList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshot) DeepCopyInto(out *DemoVirtualDiskSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshot.
func (in *DemoVirtualDiskSnapshot) DeepCopy() *DemoVirtualDiskSnapshot {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotList) DeepCopyInto(out *DemoVirtualDiskSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualDiskSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotList.
func (in *DemoVirtualDiskSnapshotList) DeepCopy() *DemoVirtualDiskSnapshotList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotSpec) DeepCopyInto(out *DemoVirtualDiskSnapshotSpec) {
	*out = *in
	in.SourceRef.DeepCopyInto(&out.SourceRef)
	if in.DataSource != nil {
		in, out := &in.DataSource, &out.DataSource
		*out = new(SnapshotDataImportRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotSpec.
func (in *DemoVirtualDiskSnapshotSpec) DeepCopy() *DemoVirtualDiskSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotStatus) DeepCopyInto(out *DemoVirtualDiskSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotStatus.
func (in *DemoVirtualDiskSnapshotStatus) DeepCopy() *DemoVirtualDiskSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSpec) DeepCopyInto(out *DemoVirtualDiskSpec) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DataSource != nil {
		in, out := &in.DataSource, &out.DataSource
		*out = new(DemoVirtualDiskDataSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSpec.
func (in *DemoVirtualDiskSpec) DeepCopy() *DemoVirtualDiskSpec {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskStatus) DeepCopyInto(out *DemoVirtualDiskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PersistentVolumeClaimRef != nil {
		in, out := &in.PersistentVolumeClaimRef, &out.PersistentVolumeClaimRef
		*out = new(DemoObjectRef)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskStatus.
func (in *DemoVirtualDiskStatus) DeepCopy() *DemoVirtualDiskStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachine) DeepCopyInto(out *DemoVirtualMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachine.
func (in *DemoVirtualMachine) DeepCopy() *DemoVirtualMachine {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineList) DeepCopyInto(out *DemoVirtualMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineList.
func (in *DemoVirtualMachineList) DeepCopy() *DemoVirtualMachineList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshot) DeepCopyInto(out *DemoVirtualMachineSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshot.
func (in *DemoVirtualMachineSnapshot) DeepCopy() *DemoVirtualMachineSnapshot {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotList) DeepCopyInto(out *DemoVirtualMachineSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualMachineSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotList.
func (in *DemoVirtualMachineSnapshotList) DeepCopy() *DemoVirtualMachineSnapshotList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotSpec) DeepCopyInto(out *DemoVirtualMachineSnapshotSpec) {
	*out = *in
	in.SourceRef.DeepCopyInto(&out.SourceRef)
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(storagev1alpha1.SnapshotImportSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotSpec.
func (in *DemoVirtualMachineSnapshotSpec) DeepCopy() *DemoVirtualMachineSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotStatus) DeepCopyInto(out *DemoVirtualMachineSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ChildrenSnapshotRefs != nil {
		in, out := &in.ChildrenSnapshotRefs, &out.ChildrenSnapshotRefs
		*out = make([]storagev1alpha1.SnapshotChildRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotStatus.
func (in *DemoVirtualMachineSnapshotStatus) DeepCopy() *DemoVirtualMachineSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSpec) DeepCopyInto(out *DemoVirtualMachineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSpec.
func (in *DemoVirtualMachineSpec) DeepCopy() *DemoVirtualMachineSpec {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineStatus) DeepCopyInto(out *DemoVirtualMachineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(DemoObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineStatus.
func (in *DemoVirtualMachineStatus) DeepCopy() *DemoVirtualMachineStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDataImportRef) DeepCopyInto(out *SnapshotDataImportRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDataImportRef.
func (in *SnapshotDataImportRef) DeepCopy() *SnapshotDataImportRef {
	if in == nil {
		return nil
	}
	out := new(SnapshotDataImportRef)
	in.DeepCopyInto(out)
	return out
}
