//go:build !ignore_autogenerated

/*
Copyright 2024 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	storagev1alpha1 "github.com/deckhouse/state-snapshotter/api/storage/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDisk) DeepCopyInto(out *DemoVirtualDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDisk.
func (in *DemoVirtualDisk) DeepCopy() *DemoVirtualDisk {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskList) DeepCopyInto(out *DemoVirtualDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskList.
func (in *DemoVirtualDiskList) DeepCopy() *DemoVirtualDiskList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshot) DeepCopyInto(out *DemoVirtualDiskSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshot.
func (in *DemoVirtualDiskSnapshot) DeepCopy() *DemoVirtualDiskSnapshot {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotContent) DeepCopyInto(out *DemoVirtualDiskSnapshotContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotContent.
func (in *DemoVirtualDiskSnapshotContent) DeepCopy() *DemoVirtualDiskSnapshotContent {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskSnapshotContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotContentList) DeepCopyInto(out *DemoVirtualDiskSnapshotContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualDiskSnapshotContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotContentList.
func (in *DemoVirtualDiskSnapshotContentList) DeepCopy() *DemoVirtualDiskSnapshotContentList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskSnapshotContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotList) DeepCopyInto(out *DemoVirtualDiskSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualDiskSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotList.
func (in *DemoVirtualDiskSnapshotList) DeepCopy() *DemoVirtualDiskSnapshotList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualDiskSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotSpec) DeepCopyInto(out *DemoVirtualDiskSnapshotSpec) {
	*out = *in
	out.RootNamespaceSnapshotRef = in.RootNamespaceSnapshotRef
	if in.ParentDemoVirtualMachineSnapshotRef != nil {
		in, out := &in.ParentDemoVirtualMachineSnapshotRef, &out.ParentDemoVirtualMachineSnapshotRef
		*out = new(storagev1alpha1.SnapshotSubjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotSpec.
func (in *DemoVirtualDiskSnapshotSpec) DeepCopy() *DemoVirtualDiskSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualDiskSnapshotStatus) DeepCopyInto(out *DemoVirtualDiskSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualDiskSnapshotStatus.
func (in *DemoVirtualDiskSnapshotStatus) DeepCopy() *DemoVirtualDiskSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualDiskSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachine) DeepCopyInto(out *DemoVirtualMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachine.
func (in *DemoVirtualMachine) DeepCopy() *DemoVirtualMachine {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineList) DeepCopyInto(out *DemoVirtualMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineList.
func (in *DemoVirtualMachineList) DeepCopy() *DemoVirtualMachineList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshot) DeepCopyInto(out *DemoVirtualMachineSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshot.
func (in *DemoVirtualMachineSnapshot) DeepCopy() *DemoVirtualMachineSnapshot {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotContent) DeepCopyInto(out *DemoVirtualMachineSnapshotContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotContent.
func (in *DemoVirtualMachineSnapshotContent) DeepCopy() *DemoVirtualMachineSnapshotContent {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineSnapshotContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotContentList) DeepCopyInto(out *DemoVirtualMachineSnapshotContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualMachineSnapshotContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotContentList.
func (in *DemoVirtualMachineSnapshotContentList) DeepCopy() *DemoVirtualMachineSnapshotContentList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineSnapshotContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotContentStatus) DeepCopyInto(out *DemoVirtualMachineSnapshotContentStatus) {
	*out = *in
	if in.ChildrenSnapshotContentRefs != nil {
		in, out := &in.ChildrenSnapshotContentRefs, &out.ChildrenSnapshotContentRefs
		*out = make([]storagev1alpha1.NamespaceSnapshotContentChildRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotContentStatus.
func (in *DemoVirtualMachineSnapshotContentStatus) DeepCopy() *DemoVirtualMachineSnapshotContentStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotContentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotList) DeepCopyInto(out *DemoVirtualMachineSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoVirtualMachineSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotList.
func (in *DemoVirtualMachineSnapshotList) DeepCopy() *DemoVirtualMachineSnapshotList {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoVirtualMachineSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotSpec) DeepCopyInto(out *DemoVirtualMachineSnapshotSpec) {
	*out = *in
	out.RootNamespaceSnapshotRef = in.RootNamespaceSnapshotRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotSpec.
func (in *DemoVirtualMachineSnapshotSpec) DeepCopy() *DemoVirtualMachineSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoVirtualMachineSnapshotStatus) DeepCopyInto(out *DemoVirtualMachineSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ChildrenSnapshotRefs != nil {
		in, out := &in.ChildrenSnapshotRefs, &out.ChildrenSnapshotRefs
		*out = make([]storagev1alpha1.NamespaceSnapshotChildRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoVirtualMachineSnapshotStatus.
func (in *DemoVirtualMachineSnapshotStatus) DeepCopy() *DemoVirtualMachineSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(DemoVirtualMachineSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}
