/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package tests

import (
	"bytes"
	"context"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"encoding/hex"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"strings"
	"time"
)

// --- External publish path over net/http (runner-local, no base cluster) --------------------------
//
// The DataExport/DataImport/manifests publish specs assert the EXTERNAL path — a request to the origin
// ingress host (api.<publicDomain>, TLS terminated at nginx) carrying only a nested SA Bearer token. On a
// nested-VM topology (alwaysCreateNew) that request is issued by a curl-runner pod on the PARENT cluster,
// which shares the DVP network with the nested VMs (the test runner reaches the nested cluster only via an
// SSH tunnel to its API, so it cannot hit the nested workers' :443 itself).
//
// On alwaysUseExisting / baremetal there is NO parent cluster and no nested-VM network — but the origin
// ingress is a real, internet-exposed host, so the test runner can reach it DIRECTLY. This file is that
// path: when externalRunsLocally() is true, the external curl helpers dispatch here and issue the request
// in-process with net/http instead of exec-ing curl in a pod. The Go client reproduces the exact curl
// semantics the external path used:
//   - InsecureSkipVerify (curl `-k`): external TLS terminates at nginx with the origin self-signed cert,
//     not the exporter/importer CA, so the external path never validated the chain.
//   - Bearer token as the only credential (Authorization header), never a runner identity.
//   - optional host->IP override (the curl `--resolve api.<host>:443:<ip>` role), from
//     E2E_PUBLISH_EXTERNAL_HOST_IP or the sslip.io masterIP; empty means plain DNS from the runner.
//   - a client certificate on the handshake for the "client certs do not authenticate through the
//     ingress" negative (no Bearer token).
//
// The DataImport upload payload, which the pod path generated inside the runner pod, is generated in
// memory here (generateLocalPayload) and registered by in-pod path so the PUT can source its body from
// localPayloadStore.

// externalHostIPOverrideEnv forces the publish host to resolve to a specific IP from the test runner,
// folding in the curl `--resolve` role for environments where the origin ingress host is not resolvable by
// the runner's DNS (e.g. a private domain). Empty (the default) uses plain DNS.
const externalHostIPOverrideEnv = "E2E_PUBLISH_EXTERNAL_HOST_IP"

// localPayloadStore holds in-memory upload payloads generated by generateLocalPayload, keyed by the in-pod
// path the specs pass as curlRequest.dataFile. It lets the local PUT source its body without a runner pod.
// The publish specs run serially in a single Ordered container, so no concurrent access occurs.
var localPayloadStore = map[string][]byte{}

// externalRunsLocally reports whether the external publish checks must run in-process (net/http) from the
// test runner instead of via a base-cluster curl pod. True exactly when there is no parent (base) cluster
// handle — the alwaysUseExisting / baremetal case (baseClusterKubeconfig would fail). On a nested-VM
// alwaysCreateNew run the base cluster is present and the pod path is used.
func externalRunsLocally() bool {
	return suiteClusterResources == nil || suiteClusterResources.BaseKubeconfig == nil
}

// externalHostIPOverride returns the IP the publish host must resolve to from the runner, or "" for plain
// DNS. Primary: E2E_PUBLISH_EXTERNAL_HOST_IP (explicit, for any environment). Fallback: the sslip.io
// masterIP parsed by the BeforeSuite publish sanity-check (the same value the pod path fed curl `--resolve`).
func externalHostIPOverride() string {
	if ip := strings.TrimSpace(os.Getenv(externalHostIPOverrideEnv)); ip != "" {
		return ip
	}
	return strings.TrimSpace(suitePublishInfra.masterIP)
}

// localHTTPClient builds the in-process client for the external publish path. TLS verification is disabled
// (curl `-k`: nginx serves the origin self-signed cert, not the exporter/importer CA). When certPEM/keyPEM
// are supplied they are presented as a client certificate on the handshake (the client-cert negative).
// When externalHostIPOverride is set, the dialer rewrites the destination IP (the curl `--resolve` role);
// the client is only ever used against the publish host, so the rewrite is unconditional.
func localHTTPClient(certPEM, keyPEM []byte) *http.Client {
	tlsCfg := &tls.Config{InsecureSkipVerify: true} //nolint:gosec // external TLS terminates at nginx with the origin self-signed cert (curl -k parity); the credential under test is the Bearer token
	if len(certPEM) > 0 && len(keyPEM) > 0 {
		if cert, err := tls.X509KeyPair(certPEM, keyPEM); err == nil {
			tlsCfg.Certificates = []tls.Certificate{cert}
		}
	}
	dialer := &net.Dialer{Timeout: 30 * time.Second, KeepAlive: 30 * time.Second}
	override := externalHostIPOverride()
	transport := &http.Transport{
		TLSClientConfig:       tlsCfg,
		TLSHandshakeTimeout:   30 * time.Second,
		ExpectContinueTimeout: 5 * time.Second,
		DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			if override != "" {
				if _, port, err := net.SplitHostPort(addr); err == nil {
					addr = net.JoinHostPort(override, port)
				}
			}
			return dialer.DialContext(ctx, network, addr)
		},
	}
	// No client-level Timeout: request lifetime is bounded by the caller's context (some downloads are
	// large and use the spec's multi-minute budget). Transport-level dial/handshake timeouts guard against
	// a wedged connection.
	return &http.Client{Transport: transport}
}

// localHTTPRequest performs one external request in-process and returns the HTTP status code and response
// body. It mirrors runCurlRequest (no `-f`, so a 4xx returns the code for the negative specs). A PUT/POST
// body is sourced from localPayloadStore keyed by r.dataFile (the in-memory upload payload); Expect:
// 100-continue lets the server reject a token-less upload before the body is transferred, matching curl.
func localHTTPRequest(ctx context.Context, rawURL string, r curlRequest) (int, string, error) {
	var body io.Reader
	contentLen := int64(-1)
	if r.dataFile != "" {
		payload, ok := localPayloadStore[r.dataFile]
		if !ok {
			return 0, "", fmt.Errorf("local external upload of %s: no in-memory payload registered for %q (generateRandomFileInPod must run in local mode first)", rawURL, r.dataFile)
		}
		body = bytes.NewReader(payload)
		contentLen = int64(len(payload))
	}

	method := strings.ToUpper(strings.TrimSpace(r.method))
	if method == "" {
		method = http.MethodGet
	}
	req, err := http.NewRequestWithContext(ctx, method, rawURL, body)
	if err != nil {
		return 0, "", fmt.Errorf("build %s %s: %w", method, rawURL, err)
	}
	if contentLen >= 0 {
		req.ContentLength = contentLen
		// Mirror curl's Expect: 100-continue on an upload so a token-less/denied PUT is rejected before the
		// body is sent (leaves the target block device untouched for the authorized retry).
		req.Header.Set("Expect", "100-continue")
	}
	if r.token != "" {
		req.Header.Set("Authorization", "Bearer "+r.token)
	}
	for _, k := range sortedKeys(r.headers) {
		req.Header.Set(k, r.headers[k])
	}

	resp, err := localHTTPClient(nil, nil).Do(req)
	if err != nil {
		return 0, "", fmt.Errorf("local external %s %s: %w", method, rawURL, err)
	}
	defer resp.Body.Close()
	b, rerr := io.ReadAll(resp.Body)
	if rerr != nil {
		return resp.StatusCode, "", fmt.Errorf("read response body from %s: %w", rawURL, rerr)
	}
	return resp.StatusCode, string(b), nil
}

// localHTTPChecksum streams a GET response through sha256 in-process and returns the hex digest, mirroring
// runCurlChecksum's `-f | sha256sum` (a >=400 response is an error, never hashed as data). The body is
// streamed straight into the hash so a large payload is never buffered whole on the runner.
func localHTTPChecksum(ctx context.Context, rawURL string, r curlRequest) (string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return "", fmt.Errorf("build GET %s: %w", rawURL, err)
	}
	if r.token != "" {
		req.Header.Set("Authorization", "Bearer "+r.token)
	}
	for _, k := range sortedKeys(r.headers) {
		req.Header.Set(k, r.headers[k])
	}
	resp, err := localHTTPClient(nil, nil).Do(req)
	if err != nil {
		return "", fmt.Errorf("local external stream GET %s: %w", rawURL, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return "", fmt.Errorf("streaming %s failed: HTTP %d (auth/transport)", rawURL, resp.StatusCode)
	}
	h := sha256.New()
	if _, cerr := io.Copy(h, resp.Body); cerr != nil {
		return "", fmt.Errorf("stream %s into sha256: %w", rawURL, cerr)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// localClientCertProbe issues a GET presenting a client certificate and NO Bearer token, returning the HTTP
// status code. It proves client certs do not authenticate through the ingress (nginx terminates TLS, so
// the cert never reaches the exporter's VerifyClientCertIfGiven) — the in-process counterpart of
// runExternalClientCertProbe's curl `--cert/--key`.
func localClientCertProbe(ctx context.Context, rawURL string, certPEM, keyPEM []byte) (int, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return 0, fmt.Errorf("build client-cert GET %s: %w", rawURL, err)
	}
	resp, err := localHTTPClient(certPEM, keyPEM).Do(req)
	if err != nil {
		return 0, fmt.Errorf("local external client-cert probe %s: %w", rawURL, err)
	}
	defer resp.Body.Close()
	_, _ = io.Copy(io.Discard, resp.Body)
	return resp.StatusCode, nil
}

// generateLocalPayload creates a random `mib`-MiB payload in memory, registers it under `path` (the key the
// local PUT reads via curlRequest.dataFile), and returns its sha256 hex digest. It is the runner-local
// counterpart of generateRandomFileInPod's in-pod `dd if=/dev/urandom | sha256sum`; the digest is what the
// restore-probe read-back compares against, so it must be computed over the exact uploaded bytes.
func generateLocalPayload(path string, mib int) (string, error) {
	buf := make([]byte, mib*1024*1024)
	if _, err := io.ReadFull(cryptorand.Reader, buf); err != nil {
		return "", fmt.Errorf("generate %d MiB random payload: %w", mib, err)
	}
	sum := sha256.Sum256(buf)
	localPayloadStore[path] = buf
	return hex.EncodeToString(sum[:]), nil
}
