apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
    appProtocol: https
  - port: 8080
    targetPort: metrics
    protocol: TCP
    name: metrics
  - port: 8081
    targetPort: health
    protocol: TCP
    name: health
  selector:
    app: controller

