{{- if and .Values.stateSnapshotter.enableDemoDomain .Values.stateSnapshotter.internal.domainApiServerCert.ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: state-snapshotter-domain-tls-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "domain-controller")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.stateSnapshotter.internal.domainApiServerCert.ca | b64enc | quote }}
  tls.crt: {{ .Values.stateSnapshotter.internal.domainApiServerCert.crt | b64enc | quote }}
  tls.key: {{ .Values.stateSnapshotter.internal.domainApiServerCert.key | b64enc | quote }}
{{- end }}
