//go:build !ignore_autogenerated

/*
Copyright 2024 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshot) DeepCopyInto(out *NamespaceSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshot.
func (in *NamespaceSnapshot) DeepCopy() *NamespaceSnapshot {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotChildRef) DeepCopyInto(out *NamespaceSnapshotChildRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotChildRef.
func (in *NamespaceSnapshotChildRef) DeepCopy() *NamespaceSnapshotChildRef {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotChildRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotContent) DeepCopyInto(out *NamespaceSnapshotContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotContent.
func (in *NamespaceSnapshotContent) DeepCopy() *NamespaceSnapshotContent {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceSnapshotContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotContentChildRef) DeepCopyInto(out *NamespaceSnapshotContentChildRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotContentChildRef.
func (in *NamespaceSnapshotContentChildRef) DeepCopy() *NamespaceSnapshotContentChildRef {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotContentChildRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotContentList) DeepCopyInto(out *NamespaceSnapshotContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceSnapshotContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotContentList.
func (in *NamespaceSnapshotContentList) DeepCopy() *NamespaceSnapshotContentList {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceSnapshotContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotContentSpec) DeepCopyInto(out *NamespaceSnapshotContentSpec) {
	*out = *in
	out.NamespaceSnapshotRef = in.NamespaceSnapshotRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotContentSpec.
func (in *NamespaceSnapshotContentSpec) DeepCopy() *NamespaceSnapshotContentSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotContentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotContentStatus) DeepCopyInto(out *NamespaceSnapshotContentStatus) {
	*out = *in
	if in.ChildrenSnapshotContentRefs != nil {
		in, out := &in.ChildrenSnapshotContentRefs, &out.ChildrenSnapshotContentRefs
		*out = make([]NamespaceSnapshotContentChildRef, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotContentStatus.
func (in *NamespaceSnapshotContentStatus) DeepCopy() *NamespaceSnapshotContentStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotContentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotList) DeepCopyInto(out *NamespaceSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotList.
func (in *NamespaceSnapshotList) DeepCopy() *NamespaceSnapshotList {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotSpec) DeepCopyInto(out *NamespaceSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotSpec.
func (in *NamespaceSnapshotSpec) DeepCopy() *NamespaceSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSnapshotStatus) DeepCopyInto(out *NamespaceSnapshotStatus) {
	*out = *in
	if in.ChildrenSnapshotRefs != nil {
		in, out := &in.ChildrenSnapshotRefs, &out.ChildrenSnapshotRefs
		*out = make([]NamespaceSnapshotChildRef, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSnapshotStatus.
func (in *NamespaceSnapshotStatus) DeepCopy() *NamespaceSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotContent) DeepCopyInto(out *SnapshotContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotContent.
func (in *SnapshotContent) DeepCopy() *SnapshotContent {
	if in == nil {
		return nil
	}
	out := new(SnapshotContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotContentChildRef) DeepCopyInto(out *SnapshotContentChildRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotContentChildRef.
func (in *SnapshotContentChildRef) DeepCopy() *SnapshotContentChildRef {
	if in == nil {
		return nil
	}
	out := new(SnapshotContentChildRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotContentList) DeepCopyInto(out *SnapshotContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotContentList.
func (in *SnapshotContentList) DeepCopy() *SnapshotContentList {
	if in == nil {
		return nil
	}
	out := new(SnapshotContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotContentSpec) DeepCopyInto(out *SnapshotContentSpec) {
	*out = *in
	out.SnapshotRef = in.SnapshotRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotContentSpec.
func (in *SnapshotContentSpec) DeepCopy() *SnapshotContentSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotContentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotContentStatus) DeepCopyInto(out *SnapshotContentStatus) {
	*out = *in
	if in.ChildrenSnapshotContentRefs != nil {
		in, out := &in.ChildrenSnapshotContentRefs, &out.ChildrenSnapshotContentRefs
		*out = make([]SnapshotContentChildRef, len(*in))
		copy(*out, *in)
	}
	if in.DataRef != nil {
		in, out := &in.DataRef, &out.DataRef
		*out = new(SnapshotDataRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotContentStatus.
func (in *SnapshotContentStatus) DeepCopy() *SnapshotContentStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotContentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDataRef) DeepCopyInto(out *SnapshotDataRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDataRef.
func (in *SnapshotDataRef) DeepCopy() *SnapshotDataRef {
	if in == nil {
		return nil
	}
	out := new(SnapshotDataRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSubjectRef) DeepCopyInto(out *SnapshotSubjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSubjectRef.
func (in *SnapshotSubjectRef) DeepCopy() *SnapshotSubjectRef {
	if in == nil {
		return nil
	}
	out := new(SnapshotSubjectRef)
	in.DeepCopyInto(out)
	return out
}
