apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:manage:state-snapshotter:viewer
  labels:
    heritage: deckhouse
    module: state-snapshotter
    rbac.deckhouse.io/use-role: viewer
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: subsystem
    rbac.deckhouse.io/subsystem: state-snapshotter
    rbac.deckhouse.io/aggregate-to-state-snapshotter-as: manager
    rbac.deckhouse.io/aggregate-to-all-as: viewer
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/kind: manage
        rbac.deckhouse.io/aggregate-to-state-snapshotter-as: viewer
rules: []
